#export AWS_ACCESS_KEY_ID=AKIAJ42XFG7XT2EC6SQA
#export AWS_SECRET_ACCESS_KEY=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
#export AWS_REGION=ap-northeast-1
#export AWS_URI_PARAM=/myz
#export AWS_HOST=s3.${AWS_REGION}.amazonaws.com

export AWS_ACCESS_KEY_ID=9I8980NI0DE7GMBHR4AL
export AWS_SECRET_ACCESS_KEY=CoDeyVzuRtZD28T8tJpMYStgGQPG4spRT5ioT4b2
export AWS_REGION=us-east-1
export AWS_URI_PARAM=/lyb
export AWS_HOST=172.16.1.4:7480
